Init commit of Task 2
GlebMakhankov/webix-start pull request #2
Opened 2021-09-23 18:25 UTC by GlebMakhankov

Task 2 pull request

2021-09-23 18:48 UTC, AlexeyXB requested changes

2021-09-23 18:48 UTC, AlexeyXB commented on src/components/Toolbar.js
> +      id: "profileBtn",
Это id у тебя нигде не используется.

2021-09-23 18:48 UTC, AlexeyXB commented on src/components/Form.js
> +            console.log();
Тут `console.log` явно не нужен :)

2021-09-23 19:05 UTC, AlexeyXB requested changes

2021-09-23 19:05 UTC, AlexeyXB commented on src/components/Form.js
> +              $$("moviesTable").add(newEntry);
В таблице нет id, поэтому тут будет ошибка

2021-09-23 19:34 UTC, AlexeyXB requested changes

2021-09-23 19:34 UTC, AlexeyXB commented on src/components/Form.js
> +    votes: (value) => value && value < 100000,
votes и rating имеет плохие правила. В рейтинг можно ввести 0, а в votes отрицательные числа

2021-09-23 20:37 UTC, AlexeyXB approved these changes

2021-09-24 10:37 UTC, HelgaListopad requested changes

2021-09-24 10:37 UTC, HelgaListopad commented on src/components/Popup.js
> +    autowidth: true,
Не будет работать для вертикального листа - для него автоматический расчёт есть для него только по высоте строк. Это видно, даже если просто открыть попап.
Почему свойство есть в апи, но не работает: у листа есть горизонтальный режим - и вот в нём всё наоборот (`autowidth` работает, `autoheight` не применим)

2021-09-24 11:02 UTC, GlebMakhankov commented on src/components/Popup.js
> +    autowidth: true,
Убрал лишнее свойство

2021-09-24 11:18 UTC, HelgaListopad approved these changes

2021-09-24 11:22 UTC, merged