Task 5
GlebMakhankov/webix-start pull request #5
Opened 2021-09-28 16:55 UTC by GlebMakhankov

Task 5

2021-09-29 07:21 UTC, AlexeyXB requested changes
1. Есть проблема с очищением валидации формы:
- выбрать фильм в таблице
- поменять категорию
- оставить одно или более не валидных полей
- нажать кнопку "Save"
- удалить выбранный фильм
2. Проблема с удалением категории:

- создать новую категорию
- выставить новую категорию какому-либо фильму
- сохранить изменения в фильме
- удалить категорию
- в таблице фильмов выбрать измененный фильм
- на форме увидим выбранную и уже несуществующую категорию

2021-09-29 08:46 UTC, HelgaListopad requested changes

2021-09-29 08:46 UTC, HelgaListopad commented on src/components/Admin/Admin_Panel_Categories_Table.js
> +          return false;
Тут возвращать false уже нет смысла - это промис, клик/селект случился раньше и в таком виде ничего не сломается

2021-09-29 08:46 UTC, HelgaListopad commented on src/components/Dashboard/Dashboard_Movies_Form.js
> +				table.unselectAll();
Не хватает того же для Clear button - если ты очистишь форму, а селект останется на месте, новые значения из формы поменяют данные в выбранной строке.

2021-09-29 21:14 UTC, HelgaListopad approved these changes

2021-09-30 02:57 UTC, AlexeyXB approved these changes

2021-09-30 02:57 UTC, merged